# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15OvOquie3YGXTP8ZoDNbziU61PGUsJp_
"""

def test():
  print("test")
test()
